# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d41af0b8c784794454aaf1fcd2e6d0e8c25676447bb0e179780adb8a42c37d913680985a851b4a5c2c741fdc2e7d6e9b60cbe6992be2e502f7ba4b9ea6facbf1

test:
  secret_key_base: 94e5e5c500ae712fbab5fc9362b0d5313d65f748f98983564ec0b07d049dc498356ef2d33b806d23394ef652f06d6208d8d3f95a6af2c9b5c03abada999b15d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
