# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a04d6e643dba0630a4d9f2593284efd6030c3ad375e988be552b32b98515a2258640cd8b1db162b32c283cd1cc1416335acb90e611ab9753e73eeb4d9ad4b945

test:
  secret_key_base: 4c6837b046068b609695b4935b7b58a759b56c4e934c289ead6f67fb4d7e2422374e44a643849038f3e614045c705a233f584c6eec95aabd24a4a1d8ae422ef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
